### ISSUE TITLE
Installation for IDA 7.X breaks due to WoW64 redirection

### ISSUE THREAD

**Issue by bnbdr** [lucasg/idarop#1]
[IDA's now a 64 bit application](https://www.hex-rays.com/products/ida/7.0/), so `ProgramW6432` should be used instead of `ProgramFiles` to get IDA's install dir.

**Comment by lucasg** [comment]
So that's why the install script didn't worked anymore !

Thanks, I'm currently porting `idarop` to ida v7 and there is several API breakages to fix.
